// src/app/firmsync/[tenantId]/paralegal-plus/components/DraftingTab.tsx
// AI-powered legal document drafting

'use client';

import { useState } from 'react';

interface DraftingTabProps {
  tenantId: string;
  previewMode?: boolean;
}

type DocumentType = 'motion' | 'contract' | 'letter' | 'memo' | 'pleading';

export function DraftingTab({ tenantId, previewMode = false }: DraftingTabProps) {
  const [documentType, setDocumentType] = useState<DocumentType>('motion');
  const [documentPrompt, setDocumentPrompt] = useState('');
  const [generatedContent, setGeneratedContent] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);

  const documentTemplates = [
    { type: 'motion' as const, label: 'Motion', icon: '⚖️', description: 'Motions, briefs, and court filings' },
    { type: 'contract' as const, label: 'Contract', icon: '📝', description: 'Contracts and agreements' },
    { type: 'letter' as const, label: 'Letter', icon: '✉️', description: 'Demand letters and correspondence' },
    { type: 'memo' as const, label: 'Memo', icon: '📋', description: 'Legal memoranda and research notes' },
    { type: 'pleading' as const, label: 'Pleading', icon: '📄', description: 'Complaints and answers' },
  ];

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (previewMode || !documentPrompt.trim()) return;

    setIsGenerating(true);

    // Simulate AI generation delay
    await new Promise(resolve => setTimeout(resolve, 2000));

    // Mock generated content
    const mockContent = `[AI-Generated ${documentType.toUpperCase()}]

IN THE UNITED STATES DISTRICT COURT
FOR THE SOUTHERN DISTRICT OF NEW YORK

PLAINTIFF NAME,
                                    Plaintiff,
v.                                  Case No.: XX-CV-XXXXX

DEFENDANT NAME,
                                    Defendant.

MOTION FOR [RELIEF REQUESTED]

COMES NOW the Plaintiff, by and through undersigned counsel, and respectfully moves this Court for [specific relief requested], and in support thereof states as follows:

INTRODUCTION

${documentPrompt}

STATEMENT OF FACTS

[This section would contain the relevant factual background based on your input. The AI analyzes your prompt and generates appropriate content.]

LEGAL ARGUMENT

I. APPLICABLE STANDARD

The legal standard applicable to this motion is...

II. ANALYSIS

Based on the facts presented and applicable law...

CONCLUSION

For the foregoing reasons, Plaintiff respectfully requests that this Court grant the Motion for [relief].

Respectfully submitted,

[Attorney Information]
Date: ${new Date().toLocaleDateString()}

---
Generated by Paralegal+ AI on ${new Date().toLocaleString()}
This is a draft document and should be reviewed by an attorney before filing.`;

    setGeneratedContent(mockContent);
    setIsGenerating(false);
  };

  return (
    <div className="space-y-6">
      {/* Document Type Selection */}
      <div className="bg-white rounded-lg border border-gray-200 p-6">
        <h2 className="text-xl font-semibold text-gray-900 mb-4">AI Document Drafting</h2>
        <p className="text-gray-600 mb-6">
          Generate legal documents using AI. Select a document type and provide details.
        </p>

        <div className="grid grid-cols-2 md:grid-cols-5 gap-3 mb-6">
          {documentTemplates.map((template) => (
            <button
              key={template.type}
              onClick={() => setDocumentType(template.type)}
              className={`p-4 rounded-lg border-2 transition-all ${
                documentType === template.type
                  ? 'border-blue-600 bg-blue-50'
                  : 'border-gray-200 hover:border-gray-300'
              }`}
              disabled={previewMode}
            >
              <div className="text-3xl mb-2">{template.icon}</div>
              <div className="font-semibold text-sm text-gray-900">{template.label}</div>
              <div className="text-xs text-gray-500 mt-1">{template.description}</div>
            </button>
          ))}
        </div>

        <form onSubmit={handleGenerate} className="space-y-4">
          <div>
            <label htmlFor="document-prompt" className="block text-sm font-medium text-gray-700 mb-2">
              Document Details
            </label>
            <textarea
              id="document-prompt"
              rows={6}
              value={documentPrompt}
              onChange={(e) => setDocumentPrompt(e.target.value)}
              placeholder={`Describe the ${documentType} you want to create. Include key facts, parties involved, relief sought, and any specific requirements...`}
              className="w-full border border-gray-300 rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
              disabled={previewMode || isGenerating}
            />
          </div>

          <div className="flex justify-end space-x-3">
            <button
              type="button"
              onClick={() => {
                setDocumentPrompt('');
                setGeneratedContent('');
              }}
              disabled={previewMode || isGenerating}
              className="px-4 py-2 border border-gray-300 rounded-md text-gray-700 hover:bg-gray-50"
            >
              Clear
            </button>
            <button
              type="submit"
              disabled={previewMode || !documentPrompt.trim() || isGenerating}
              className={`px-6 py-2 rounded-md font-medium ${
                previewMode || !documentPrompt.trim() || isGenerating
                  ? 'bg-gray-100 text-gray-400 cursor-not-allowed'
                  : 'bg-blue-600 text-white hover:bg-blue-700'
              }`}
            >
              {isGenerating ? (
                <span className="flex items-center">
                  <svg className="animate-spin -ml-1 mr-2 h-4 w-4 text-white" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                  </svg>
                  Generating...
                </span>
              ) : (
                'Generate Document'
              )}
            </button>
          </div>
        </form>
      </div>

      {/* Generated Content */}
      {generatedContent && (
        <div className="bg-white rounded-lg border border-gray-200 p-6">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-lg font-semibold text-gray-900">Generated Document</h3>
            <div className="flex space-x-2">
              <button className="px-3 py-1 text-sm bg-blue-600 text-white rounded-md hover:bg-blue-700">
                Copy to Clipboard
              </button>
              <button className="px-3 py-1 text-sm border border-gray-300 text-gray-700 rounded-md hover:bg-gray-50">
                Download as DOCX
              </button>
              <button className="px-3 py-1 text-sm border border-gray-300 text-gray-700 rounded-md hover:bg-gray-50">
                Save to Case
              </button>
            </div>
          </div>

          <div className="bg-gray-50 border border-gray-200 rounded-md p-6 font-mono text-sm whitespace-pre-wrap">
            {generatedContent}
          </div>

          <div className="mt-4 p-4 bg-amber-50 border border-amber-200 rounded-md">
            <div className="flex">
              <svg className="w-5 h-5 text-amber-600 mr-2" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
              </svg>
              <div>
                <p className="text-sm font-medium text-amber-800">AI-Generated Content</p>
                <p className="text-sm text-amber-700 mt-1">
                  This document was generated by AI and should be thoroughly reviewed and edited by a licensed attorney before use.
                </p>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Recent Drafts */}
      <div className="bg-white rounded-lg border border-gray-200 p-6">
        <h3 className="text-lg font-semibold text-gray-900 mb-4">Recent Drafts</h3>
        <div className="space-y-3">
          {[
            { name: 'Motion to Dismiss - Smith v. Johnson', date: '2024-01-20', type: 'Motion' },
            { name: 'Settlement Agreement - Brown Case', date: '2024-01-18', type: 'Contract' },
            { name: 'Demand Letter - Davis Collection', date: '2024-01-15', type: 'Letter' },
          ].map((draft, index) => (
            <div
              key={index}
              className="flex items-center justify-between p-3 border border-gray-200 rounded-lg hover:border-blue-300 transition-colors"
            >
              <div className="flex items-center">
                <div className="w-10 h-10 bg-blue-100 rounded-lg flex items-center justify-center mr-3">
                  <svg className="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                </div>
                <div>
                  <p className="font-medium text-gray-900">{draft.name}</p>
                  <p className="text-sm text-gray-500">
                    {draft.type} • {new Date(draft.date).toLocaleDateString()}
                  </p>
                </div>
              </div>
              <button className="text-sm text-blue-600 hover:text-blue-800 font-medium">
                Open
              </button>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
